/* Generated By:JavaCC: Do not edit this line. ChineseTokenizerConstants.java */
/* 
 * Copyright (c) 2008, National Institute of Informatics
 *
 * This file is part of SRL, and is free
 * software, licenced under the GNU Library General Public License,
 * Version 2, June 1991.
 *
 * A copy of this licence is included in the distribution in the file
 * licence.html, and is also available at http://www.fsf.org/licensing/licenses/info/GPLv2.html.
*/
package srl.corpus.zh;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ChineseTokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUM = 1;
  /** RegularExpression Id. */
  int BEGIN_TAG = 2;
  /** RegularExpression Id. */
  int END_TAG = 3;
  /** RegularExpression Id. */
  int APOSTROPHE = 4;
  /** RegularExpression Id. */
  int ACRONYM = 5;
  /** RegularExpression Id. */
  int COMPANY = 6;
  /** RegularExpression Id. */
  int EMAIL = 7;
  /** RegularExpression Id. */
  int HOST = 8;
  /** RegularExpression Id. */
  int NUM = 9;
  /** RegularExpression Id. */
  int PUNCTUATION = 10;
  /** RegularExpression Id. */
  int P = 11;
  /** RegularExpression Id. */
  int HAS_DIGIT = 12;
  /** RegularExpression Id. */
  int ALPHA = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int PUNC = 15;
  /** RegularExpression Id. */
  int CJ = 16;
  /** RegularExpression Id. */
  int SPACE = 17;
  /** RegularExpression Id. */
  int KOREAN = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int NOISE = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<BEGIN_TAG>",
    "<END_TAG>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<PUNCTUATION>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<PUNC>",
    "<CJ>",
    "<SPACE>",
    "<KOREAN>",
    "<DIGIT>",
    "<NOISE>",
  };

}
