/* Generated By:JavaCC: Do not edit this line. PreTokenizerConstants.java */
/* 
 * Copyright (c) 2008, National Institute of Informatics
 *
 * This file is part of SRL, and is free
 * software, licenced under the GNU Library General Public License,
 * Version 2, June 1991.
 *
 * A copy of this licence is included in the distribution in the file
 * licence.html, and is also available at http://www.fsf.org/licensing/licenses/info/GPLv2.html.
*/
package srl.corpus.pre;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PreTokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN_TAG = 1;
  /** RegularExpression Id. */
  int END_TAG = 2;
  /** RegularExpression Id. */
  int SPLITTER = 3;
  /** RegularExpression Id. */
  int ANYTHING = 4;
  /** RegularExpression Id. */
  int ALPHANUM = 5;
  /** RegularExpression Id. */
  int NOISE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<BEGIN_TAG>",
    "<END_TAG>",
    "<SPLITTER>",
    "<ANYTHING>",
    "<ALPHANUM>",
    "\" \"",
  };

}
